### PR TITLE
Api/set score validation

### PR DESCRIPTION
**Pull request by aurelien-cuvelier**
## Description

I implemented a basic API cryptographic call validation so that the back-end can validate that set score requests from the front-end, and verify that the content has not been altered by someone (setting higher score for example). This is done by calculating a sha256 digest of the payload (stringified in a deterministic way) + an api secret that is shared between both front & back.

## Related Issue
https://github.com/portdeveloper/slot-machine-monorepo/issues/1

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Discord/Telegram handle

aurel_dev0x1 (discord)

### CODE REVIEW

**Comment by portdeveloper** [comment]
I think this PR looks and works great! @aurelien-cuvelier 

But do you think if it could be any better if we used another method to handle env vars?

Because I believe that we should let people use `deploy:all` and `deploy:frontend` scripts.

Currently, if I do a "pnpm run deploy:frontend", we are naturally missing the env vars

let me know if im mistaken!

**Comment by aurelien-cuvelier** [comment]
> I think this PR looks and works great! @aurelien-cuvelier
> 
> But do you think if it could be any better if we used another method to handle env vars?
> 
> Because I believe that we should let people use `deploy:all` and `deploy:frontend` scripts.
> 
> Currently, if I do a "pnpm run deploy:frontend", we are naturally missing the env vars
> 
> let me know if im mistaken!

Hey @portdeveloper, first of all thanks your comment. I never worked with fly.io before, for deployment i followed the instructions that were i the readme, but some steps were missing, like there was no mention on how to set-up env var for the container deployed on fly.io, so i pretty much assumed that this part was left on purpose at the "dev discretion" let's say, and i set it up on my end.

But now the question i have for you (or who ever worked on that before), is the following: Were the env variables already set-up for you automatically when you just ran these commands in the readme (for depoyment)? Or did you have to manually set-up using the fly.io secret system? 

I am asking this because, since there was no effective .gitignore file ignoring .env files through the project, i am actually wondering if fly.io wasn't also copying your .env files for the production image, which would lead to setting up env var for you (which is maybe why there is no mention about setting up env var in the fly.io cli commands). But now since a .gitignore file has been included, maybe this is what is creating friction on the current deployment process about env var, and therefore the deployment instructions should be re-thought, because there were based on a deployment without the presence of a .gitignore file. Do you follow me?

**Comment by portdeveloper** [comment]
I thought I sent a comment here lol, sorry for commenting so late @aurelien-cuvelier !

The way I usually set env vars is this
1. I launch the app with `flyctl launch`
2. I go to the relevant project e.g. `https://fly.io/apps/slot-machine-frontend` and set the env vars there
3. I re-deploy the app with `fly deploy`

This is a one-time thing that wouldn't cause problems even if we let people do it manually. Whether they use the frontend or not, it will still be two deployments for fly to recognize the env vars.

More context on it: https://fly.io/docs/apps/secrets/#set-secrets

Currently I do not know any other way to handle this without introducing some overhead.

**Comment by aurelien-cuvelier** [comment]
Hey @portdeveloper, no worries, i'm also late !

I also had set manually env variables for the front like this, but it did not want to work for me. Anyway i think this causes a lot of friction for deployment, so i set up a new deployment workflow which i believe is way better than the current one.

For both apps (back & front) they now have a bash deployment script, which is taking care of the deployment part for us. The scripts will deploy using flyctl and directly feed in the CLI the variables present in the corresponding .env of the app, so no need to set them up manually on flyio anymore, it's all being taken cared of automatically by these scripts. 

I also updated the README in order to explain a bit how to get new env var ready for deployment if someone wants to add any later on, let me know what you think !

**Comment by portdeveloper** [comment]
SO GOOOD!!! LGTM

**Pull request merged**
